"use client";

import { useState, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSummaryStore, LOADING_MESSAGES } from "@/store/summaryStore";
import { useAuthStore } from "@/store/authStore";
import { api } from "@/lib/api";
import { wordCount, estimateReadingTime, formatSeconds, getReadabilityLabel, getSentimentColor, truncateText } from "@/lib/utils";
import {
  FileText, Link2, Upload, Sparkles, Copy, Download, RefreshCw,
  ChevronDown, List, AlignLeft, Clock, BarChart3, Hash, TrendingUp,
  CheckCircle2, AlertCircle, Loader2, X, Star,
} from "lucide-react";

const lengthOptions = [
  { value: "short" as const, label: "Short", desc: "~60 words" },
  { value: "medium" as const, label: "Medium", desc: "~128 words" },
  { value: "detailed" as const, label: "Detailed", desc: "~256 words" },
];

export default function SummarizePage() {
  const store = useSummaryStore();
  const { token } = useAuthStore();
  const [copied, setCopied] = useState(false);
  const [loadingIdx, setLoadingIdx] = useState(0);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleSummarize = useCallback(async () => {
    store.setLoading(true, LOADING_MESSAGES[0]);
    setLoadingIdx(0);
    const interval = setInterval(() => {
      setLoadingIdx((i) => {
        const next = Math.min(i + 1, LOADING_MESSAGES.length - 1);
        store.setLoading(true, LOADING_MESSAGES[next]);
        return next;
      });
    }, 2000);

    try {
      let result;
      if (store.inputMode === "url") {
        result = await api.summarizeURL({ url: store.inputURL, length: store.summaryLength, bullet_mode: store.bulletMode }, token);
      } else if (store.inputMode === "file" && store.inputFile) {
        result = await api.summarizeFile(store.inputFile, store.summaryLength, store.bulletMode, token);
      } else {
        result = await api.summarizeText({ text: store.inputText, length: store.summaryLength, bullet_mode: store.bulletMode }, token);
      }
      store.setResult(result);
    } catch (e: any) {
      store.setError(e.message || "Summarization failed");
    } finally {
      clearInterval(interval);
    }
  }, [store, token]);

  const handleCopy = () => {
    if (store.result) {
      navigator.clipboard.writeText(store.result.summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!store.result) return;
    const content = `# ${store.result.headline || "Summary"}\n\n${store.result.summary}\n\n## Key Points\n${store.result.key_points.map((p) => `- ${p}`).join("\n")}\n\n---\nGenerated by Briefly`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "summary.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) store.setInputFile(file);
  };

  const canSubmit = store.inputMode === "text" ? store.inputText.length >= 50 : store.inputMode === "url" ? store.inputURL.length >= 10 : !!store.inputFile;
  const inputWords = store.inputMode === "text" ? wordCount(store.inputText) : 0;

  const s = { section: { maxWidth: "1280px", margin: "0 auto", padding: "32px 24px" } as React.CSSProperties };

  return (
    <div style={s.section}>
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: "32px" }}>
        <h1 className="text-heading-2">Summarize</h1>
        <p style={{ color: "var(--text-tertiary)", marginTop: "4px", fontSize: "0.9375rem" }}>
          Paste text, a URL, or upload a document to get an AI-generated summary.
        </p>
      </motion.div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px", alignItems: "start" }} className="summarize-grid">
        {/* ── LEFT: INPUT PANEL ── */}
        <motion.div initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
          {/* Mode Tabs */}
          <div style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "var(--radius-md)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-subtle)" }}>
            {([["text", "Text", FileText], ["url", "URL", Link2], ["file", "File", Upload]] as const).map(([mode, label, Icon]) => (
              <button key={mode} onClick={() => store.setInputMode(mode)} style={{
                flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: "6px", padding: "10px", borderRadius: "var(--radius-sm)", border: "none", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer",
                backgroundColor: store.inputMode === mode ? "var(--bg-card)" : "transparent",
                color: store.inputMode === mode ? "var(--text-primary)" : "var(--text-muted)",
                boxShadow: store.inputMode === mode ? "var(--shadow-sm)" : "none", transition: "all 0.2s ease",
              }}>
                <Icon size={14} /> {label}
              </button>
            ))}
          </div>

          {/* Input Area */}
          <div style={{ borderRadius: "var(--radius-lg)", border: "1px solid var(--border-subtle)", backgroundColor: "var(--bg-card)", overflow: "hidden" }}>
            {store.inputMode === "text" && (
              <div style={{ position: "relative" }}>
                <textarea value={store.inputText} onChange={(e) => store.setInputText(e.target.value)} placeholder="Paste your article text here... (minimum 50 characters)" style={{
                  width: "100%", minHeight: "340px", padding: "20px", border: "none", outline: "none", resize: "vertical",
                  fontFamily: "var(--font-sans)", fontSize: "0.9375rem", lineHeight: 1.7, backgroundColor: "transparent", color: "var(--text-primary)",
                }} />
                <div style={{ padding: "8px 20px 12px", display: "flex", justifyContent: "space-between", borderTop: "1px solid var(--border-subtle)", fontSize: "0.75rem", color: "var(--text-muted)" }}>
                  <span>{inputWords} words</span>
                  <span>~{estimateReadingTime(inputWords)} min read</span>
                </div>
              </div>
            )}
            {store.inputMode === "url" && (
              <div style={{ padding: "20px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "14px 16px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-input)" }}>
                  <Link2 size={16} style={{ color: "var(--text-muted)", flexShrink: 0 }} />
                  <input type="url" value={store.inputURL} onChange={(e) => store.setInputURL(e.target.value)} placeholder="https://example.com/article" style={{
                    flex: 1, border: "none", outline: "none", fontSize: "0.9375rem", backgroundColor: "transparent", color: "var(--text-primary)", fontFamily: "var(--font-sans)",
                  }} />
                </div>
                <p style={{ marginTop: "12px", fontSize: "0.8125rem", color: "var(--text-muted)" }}>
                  Works with most news sites, blogs, and article pages.
                </p>
              </div>
            )}
            {store.inputMode === "file" && (
              <div style={{ padding: "20px" }}>
                <div onClick={() => fileInputRef.current?.click()} style={{
                  border: "2px dashed var(--border-default)", borderRadius: "var(--radius-md)", padding: "48px 24px", textAlign: "center", cursor: "pointer", transition: "all 0.2s ease",
                }}>
                  <Upload size={32} style={{ color: "var(--text-muted)", marginBottom: "12px" }} />
                  {store.inputFile ? (
                    <div>
                      <p style={{ fontWeight: 500, color: "var(--text-primary)" }}>{store.inputFile.name}</p>
                      <p style={{ fontSize: "0.8125rem", color: "var(--text-muted)", marginTop: "4px" }}>{(store.inputFile.size / 1024).toFixed(1)} KB</p>
                    </div>
                  ) : (
                    <div>
                      <p style={{ fontWeight: 500, color: "var(--text-secondary)" }}>Click to upload a file</p>
                      <p style={{ fontSize: "0.8125rem", color: "var(--text-muted)", marginTop: "4px" }}>PDF, DOCX, or TXT (max 10MB)</p>
                    </div>
                  )}
                </div>
                <input ref={fileInputRef} type="file" accept=".pdf,.docx,.txt" onChange={handleFileChange} style={{ display: "none" }} />
              </div>
            )}
          </div>

          {/* Controls */}
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap", alignItems: "center" }}>
            {/* Length Selector */}
            <div style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "var(--radius-md)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-subtle)" }}>
              {lengthOptions.map((opt) => (
                <button key={opt.value} onClick={() => store.setSummaryLength(opt.value)} style={{
                  padding: "8px 14px", borderRadius: "var(--radius-sm)", border: "none", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer",
                  backgroundColor: store.summaryLength === opt.value ? "var(--bg-card)" : "transparent",
                  color: store.summaryLength === opt.value ? "var(--text-primary)" : "var(--text-muted)",
                  boxShadow: store.summaryLength === opt.value ? "var(--shadow-sm)" : "none", transition: "all 0.2s ease",
                }}>
                  {opt.label}
                </button>
              ))}
            </div>

            {/* Bullet Mode */}
            <button onClick={() => store.setBulletMode(!store.bulletMode)} style={{
              display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer",
              backgroundColor: store.bulletMode ? "var(--accent-primary-light)" : "var(--bg-card)",
              color: store.bulletMode ? "var(--accent-primary)" : "var(--text-tertiary)", transition: "all 0.2s ease",
            }}>
              <List size={14} /> Bullets
            </button>
          </div>

          {/* Submit Button */}
          <button onClick={handleSummarize} disabled={!canSubmit || store.isLoading} style={{
            display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", padding: "14px 24px", borderRadius: "var(--radius-md)", border: "none",
            backgroundColor: canSubmit && !store.isLoading ? "var(--accent-primary)" : "var(--bg-tertiary)",
            color: canSubmit && !store.isLoading ? "#fff" : "var(--text-muted)",
            fontSize: "0.9375rem", fontWeight: 600, cursor: canSubmit && !store.isLoading ? "pointer" : "not-allowed", transition: "all 0.2s ease",
            boxShadow: canSubmit && !store.isLoading ? "0 2px 8px rgba(59,91,219,0.25)" : "none",
          }}>
            {store.isLoading ? <><Loader2 size={16} className="animate-spin" style={{ animation: "spin 1s linear infinite" }} /> {store.loadingMessage}</> : <><Sparkles size={16} /> Summarize</>}
          </button>

          {store.error && (
            <div style={{ display: "flex", alignItems: "center", gap: "8px", padding: "12px 16px", borderRadius: "var(--radius-md)", backgroundColor: "rgba(220,38,38,0.08)", color: "var(--accent-error)", fontSize: "0.875rem" }}>
              <AlertCircle size={16} /> {store.error}
            </div>
          )}
        </motion.div>

        {/* ── RIGHT: OUTPUT PANEL ── */}
        <motion.div initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} style={{
          borderRadius: "var(--radius-lg)", border: "1px solid var(--border-subtle)", backgroundColor: "var(--bg-card)", minHeight: "500px", display: "flex", flexDirection: "column",
        }}>
          {store.isLoading ? (
            <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "16px", padding: "48px" }}>
              <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: "linear" }}>
                <Sparkles size={32} style={{ color: "var(--accent-primary)" }} />
              </motion.div>
              <p style={{ fontSize: "0.9375rem", fontWeight: 500, color: "var(--text-secondary)" }}>{store.loadingMessage}</p>
              <div style={{ width: "200px", height: "4px", borderRadius: "var(--radius-full)", backgroundColor: "var(--bg-tertiary)", overflow: "hidden" }}>
                <motion.div animate={{ x: ["-100%", "100%"] }} transition={{ duration: 1.5, repeat: Infinity }} style={{ width: "40%", height: "100%", borderRadius: "var(--radius-full)", backgroundColor: "var(--accent-primary)" }} />
              </div>
            </div>
          ) : store.result ? (
            <div style={{ padding: "24px", display: "flex", flexDirection: "column", gap: "20px" }}>
              {/* Headline */}
              {store.result.headline && (
                <motion.h2 initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ fontFamily: "var(--font-serif)", fontSize: "1.5rem", lineHeight: 1.2, color: "var(--text-primary)" }}>
                  {store.result.headline}
                </motion.h2>
              )}

              {/* Summary Text */}
              <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} style={{ fontSize: "0.9375rem", lineHeight: 1.75, color: "var(--text-secondary)", whiteSpace: "pre-wrap" }}>
                {store.result.bullet_summary ? (
                  <ul style={{ listStyleType: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "12px" }}>
                    {store.result.bullet_summary.split("\n").map((line, i) => (
                      <li key={i} style={{ display: "flex", alignItems: "flex-start" }}>{line}</li>
                    ))}
                  </ul>
                ) : (
                  store.result.summary
                )}
              </motion.div>

              {/* Key Points */}
              {store.result.key_points.length > 0 && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }} style={{ borderTop: "1px solid var(--border-subtle)", paddingTop: "16px" }}>
                  <p style={{ fontSize: "0.6875rem", fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--text-muted)", marginBottom: "10px" }}>Key Points</p>
                  <ul style={{ listStyle: "none", padding: 0, display: "flex", flexDirection: "column", gap: "8px" }}>
                    {store.result.key_points.slice(0, 5).map((point, i) => (
                      <motion.li key={i} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 + i * 0.05 }} style={{ display: "flex", gap: "8px", fontSize: "0.875rem", color: "var(--text-tertiary)", lineHeight: 1.5 }}>
                        <CheckCircle2 size={14} style={{ color: "var(--accent-primary)", flexShrink: 0, marginTop: "3px" }} />
                        {truncateText(point, 150)}
                      </motion.li>
                    ))}
                  </ul>
                </motion.div>
              )}

              {/* Analytics Badges */}
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }} style={{ display: "flex", flexWrap: "wrap", gap: "8px", borderTop: "1px solid var(--border-subtle)", paddingTop: "16px" }}>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <TrendingUp size={12} /> {store.result.analytics.sentiment}
                </span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <Clock size={12} /> {formatSeconds(store.result.analytics.reading_time_saved)} saved
                </span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <BarChart3 size={12} /> {Math.round(store.result.analytics.confidence_score * 100)}% confidence
                </span>
                <span style={{ display: "inline-flex", alignItems: "center", gap: "4px", padding: "4px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", fontWeight: 500, backgroundColor: "var(--accent-primary-light)", color: "var(--accent-primary)" }}>
                  <Hash size={12} /> {store.result.analytics.original_word_count} → {store.result.analytics.summary_word_count} words
                </span>
              </motion.div>

              {/* Keywords */}
              {store.result.analytics.keywords.length > 0 && (
                <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                  {store.result.analytics.keywords.map((kw) => (
                    <span key={kw} style={{ padding: "3px 10px", borderRadius: "var(--radius-full)", fontSize: "0.75rem", border: "1px solid var(--border-default)", color: "var(--text-tertiary)" }}>{kw}</span>
                  ))}
                </div>
              )}

              {/* Action Buttons */}
              <div style={{ display: "flex", gap: "8px", borderTop: "1px solid var(--border-subtle)", paddingTop: "16px" }}>
                <button onClick={handleCopy} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer", color: copied ? "var(--accent-success)" : "var(--text-tertiary)", transition: "all 0.2s ease" }}>
                  {copied ? <CheckCircle2 size={14} /> : <Copy size={14} />} {copied ? "Copied" : "Copy"}
                </button>
                <button onClick={handleDownload} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer", color: "var(--text-tertiary)", transition: "all 0.2s ease" }}>
                  <Download size={14} /> Download
                </button>
                <button onClick={handleSummarize} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 14px", borderRadius: "var(--radius-md)", border: "1px solid var(--border-default)", backgroundColor: "var(--bg-card)", fontSize: "0.8125rem", fontWeight: 500, cursor: "pointer", color: "var(--text-tertiary)", transition: "all 0.2s ease" }}>
                  <RefreshCw size={14} /> Regenerate
                </button>
              </div>
            </div>
          ) : (
            /* Empty State */
            <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "48px 32px", textAlign: "center" }}>
              <div style={{ width: "64px", height: "64px", borderRadius: "var(--radius-lg)", backgroundColor: "var(--bg-secondary)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: "20px" }}>
                <FileText size={28} style={{ color: "var(--text-muted)" }} />
              </div>
              <h3 style={{ fontFamily: "var(--font-serif)", fontSize: "1.25rem", marginBottom: "8px", color: "var(--text-secondary)" }}>Your summary will appear here</h3>
              <p style={{ fontSize: "0.875rem", color: "var(--text-muted)", maxWidth: "300px", lineHeight: 1.6 }}>Paste an article, enter a URL, or upload a document to get started.</p>
            </div>
          )}
        </motion.div>
      </div>

      <style jsx global>{`
        @media (max-width: 768px) {
          .summarize-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}
